var LOCALE = {
  'EN': 'ES_es',
  'Logout': 'Salir',
  'Do you want to exit and close the session?': '¿Desea salir y cerrar la sesión?',
  'Help': 'Ayuda',
  'Menu': 'Menu',
  'News': 'Noticias',
  'User': 'Usuario',
  'Email': 'Email',
  'Name': 'Nombre',
  'Last Name': 'Apellidos',
  'Save': 'Guardar',
  'Edit': 'Editar',
  'List' : 'Lista',
  'Edit selected record': 'Editar el registro seleccionado',
  'Reset': 'Vaciar',
  'Add': 'Agregar',
  'Add record' : 'Agregar registro',
  'Delete': 'Eliminar',
  'Delete selected record': 'Eliminar el registro seleccionado',
  'Are you sure you want to delete?' : '¿Está seguro de que desea eliminarlo?',
  'Id': 'Id',
  'User List': 'Lista de Usuarios',
  'Only Browse': 'Solo Consultas' ,
  'Editor': 'Editor',
  'Administrator': 'Administrador',
  'Administration': 'Administración',
  'REMOTE EXCEPTION': 'EXCEPCIÓN REMOTA',
  'Rol': 'Rol',
  'Add User': 'Agregar Usuario',
  'Save': 'Guardar',
  'Cancel': 'Cancelar',
  'OK': 'Aceptar',
  'Yes': 'Si',
  'No': 'No',
  'Users': 'Usuarios',
  'Specialists': 'Especialistas',
  'RESCATE CONTROL PANEL': 'PANEL DE CONTROL RESCATE',
  'Start': 'Inicio',
  'Start date must be less than end date' : 'La fecha inicial debe ser anterior a la fecha final',
  'Restorers': 'Restauradores',
  'Add Restorer': 'Agregar Restaurador',
  'Edit Restorer': 'Editar Restaurador',
  'News': 'Noticias',
  'Show only my records': 'Mostrar solo mis registros',
  'Search': 'B&uacute;squeda',
  'Search by' : 'Buscar por',
  'Options': 'Opciones',
  'Users List': 'Lista de Usuarios',
  'Already In Use': 'Ya está en uso',
  'Surname':'Apellido',
  'Surname 1': 'Apellido 1',
  'Surname 2': 'Apellido 2',
  'Password': 'Contrase&ntilde;a',
  'Some fields are invalid, please check them before continue' : 'Algunos campos son inválidos, por favor revíselos antes de continuar',
  'Retype password': 'Repetir contrase&ntilde;a',
  'Details': 'Detalles',
  'Edit User': 'Editar Usuario',
  'Passwords do not match': 'Las contrase&ntilde;as no coinciden',
  'WRONG SERVER RESPONSE': 'RESPUESTA ERRÓNEA DEL SERVIDOR.<br />Compruebe que tiene conexión a internet y vuelva a intentarlo.<br />Si el problema persiste consulte a su administrador.',
  'Changes saved successfully': 'Cambios guardados correctamente',
  'Operation successfull': 'Operación correcta',
  'Are you sure?': '¿Está seguro?',
  'Confirmation' : 'Confirmación',
  'Permissions' : 'Permisos',
  'Description' : 'Descripción',
  'Roles list' : 'Lista Roles',
  'Add Rol' : 'Agregar Rol',
  'Edit Rol' : 'Editar Rol',
  'Refresh' : 'Refrescar',
  'Refreshes the list' : 'Refresca la lista',
  'Displaying {0} - {1} of {2}' : 'Mostrando {0} - {1} de {2}',
  'Nothing to display' : 'Nada que mostrar',
  'Center':'Centro',
  'Man':'Hombre',
  'Woman':'Mujer',
  'Loading...': 'Cargando...',
  'Do you want to add the relation?':'¿Desea agregar la relación?',
  'Club' : 'Asociación',
  'Clubs' : 'Asociaciones',
  'Professional-Club' : 'Fechas de Pertenencia',
  'Club Details' : 'Detalles de la Asociación',
  'Associated Clubs' : 'Pertenencia a Asociaciones',
  'Associated Bibliography' : 'Bibliografía relacionada',
  'Bibliography Autors': 'Autores Bibliografía',
  'Bibliographies List': 'Lista Bibliografías',
  'Bibliographies' : 'Bibliografías',
  'Add Club' : 'Agregar Club',
  'Bibliography':'Bibliografía',
  'Professional Details' : 'Detalles del Profesional',
  'Start Date' : 'Fecha Inicio',
  'End Date' : 'Fecha Fin',
  'Start Date (Year)' : 'Fecha Inicio (Año)',
  'End Date (Year)' : 'Fecha Fin (Año)',
  'Title' : 'Título',
  'Author' : 'Autor',
  'Author(s)': 'Autor(es)',
  'Author Name': 'Nombre Autor',
  'Authors & Related Professionals': 'Autores y Profesionales Relacionados',
  'Relation':'Relación',
  'ISBN' : 'ISBN',
  'Publisher' : 'Editorial',
  'Categories' : 'Categorías',
  'Id': 'Id',
  'Jobs List' : 'Lista de Cargos',
  'Add Job' : 'Agregar Cargo',
  'Department' : 'Departamento',
  'Main' : 'Principal',
  'Center Name' : 'Nombre del Centro',
  'Center Code' : 'Código del centro',
  'Center Details' : 'Detalles del Centro',
  'Main Job' : 'Es su cargo Principal',
  'Center' : 'Centro',
  'Type' : 'Tipo',
  'Document Type': 'Tipo de Documento',
  'Document Types': 'Tipos de Documentos',
  'Professional-Document Type': 'Profesional-Tipo de Documento',
  'Code' : 'Código',
  'Collaborator' : 'Colaborador',
  'Collaborators' : 'Colaboradores',
  'Asocciated Collaborators' : 'Colaboradores Relacionados',
  'You must edit it to complete the details' : 'Debe editarlo para añadir los detalles que faltan',
  'Professional-Specialty' : 'Profesional-Especialidad',
  'Specialities' : 'Especialidades',
  'Add Speciality' : 'Agregar Especialidad',
  'Education List' : 'Lista Formación',
  'Education' : 'Formación',
  'News List' : 'Lista de Noticias',
  'Body' : 'Cuerpo',
  'Published' : 'Publicada',
  'In Front Page' : 'En Portada',
  'Login' : 'Login',
  'Last Modification' : 'Última Modificación',
  'Creator Name' : 'Nombre Creador',
  'Creator Surname 1' : 'Apellido 1 Creador',
  'Creator Surname 2' : 'Apellido 2 Creador',
  'Country of Birth' : 'País de Nacimiento',
  'State of Birth' : 'Provincia de Nacimiento', 
  'City of Birth' : 'Ciudad de Nacimiento',
  'Country of Death' : 'País de Defunción',
  'State of Death' : 'Provincia de Defunción',
  'City of Death' : 'Población de Defunción',
  'Checked (0/1)' : 'Supervisado (0/1)',
  'Blocked (0/1)' : 'Bloqueado (0/1)',
  'Highlight': 'Resaltar',
  'Highlights non supervised records' : 'Resaltar los registros no supervisados',
  'Restorers List' : 'Lista de restauradores',
  'Specialist' : 'Especialista',
  'Restorers' : 'Restauradores',
  'General' : 'General',
  'Sex' : 'Sexo',
  'Date' : 'Fecha',
  'Date (Year)' : 'Fecha (Año)',
  'Birth Date' : 'Fecha de Nacimiento',
  'Date of Death' : 'Fecha de Defunción',
  'Birth Location' : 'Lugar de nacimiento',
  'Death Location' : 'Lugar de Defunción',
  'Me' : 'Yo',
  'Option Blocked' : 'Opción bloqueada',
  'You dont have the required permissions' : 'No tiene los permisos necesarios',
  'You must save changes before' : 'Debe guardar los cambios antes',
  'Success saving <br />Do you want to continue editing?' : 'Guardado correcto.<br />¿Desea seguir editándolo?',
  'Country' : 'País',
  'State/Province' : 'Provincia',
  'City' : 'Población',
  'Address' : 'Dirección',
  'Checked' : 'Supervisado',
  'Blocked' : 'Bloqueado',
  'Creator' : 'Creador',
  'Add Tech' : 'Agregar Técnica',
  'Technnics' : 'Técnicas',
  'Restauration Technnics' : 'Técnicas de Restauración',
  'Technnic' : 'Técnica',
  'Basic' : 'Básico',
  'Award' : 'Reconocimiento',
  'Awards' : 'Reconocimientos',
  'Awards List' : 'Lista Reconocimientos',
  'Work Of Art Name' : 'Nombre Obra',
  'Work Of Art' : 'Obra',
  'Width (cm)' : 'Anchura (cm)',
  'Height (cm)' : 'Altura (cm)',
  'Deep (cm)' : 'Profundidad (cm)',
  'Author Name' : 'Nombre Autor',
  'Author Surname 1' : 'Apellido 1 Autor',
  'Author Surname 2' : 'Apellido 2 Autor',
  'Associated Locations' : 'Ubicación asociada',
  'Location' : 'Localización',
  'Position': 'Ubicación',
  'Positions': 'Ubicaciones',
  'Original Location' : 'Localización Original',
  'Current Location' : 'Ubicación Actual',
  'Current Location State/Province': 'Provincia Ubicación Actual',
  'Current Location City': 'Población Ubicación Actual',
  'Current Location Country': 'País Ubicación Actual',
  'Current Location Name': 'Nombre Ubicación Actual',
  'Location-Work Of Art' : 'Ubicación-Obra de Arte',
  'Professionals' : 'Profesionales',
  'Server Response': 'Respuesta del Servidor',
  'Thumb': 'Min.',
  'Associated Documents' : 'Documentos Relacionados',
  'Associated Professionals' : 'Profesionales Relacionados',
  'Professional-Document' : 'Documento-Profesional',
  'Documents' : 'Documentos',
  'Select Filter' : 'Seleccione Filtro',
  'Select Comparator' : 'Seleccione Comparador',
  'Comparator' : 'Comparador',
  'LIKE' : 'Parecido',
  'NOT LIKE' : 'No parecido',
  'Distinct' : 'Distinto',
  'File' : 'Archivo',
  'Intervention' : 'Intervención',
  'Take picture and upload' : 'Capturar imagen',
  'Upload' : 'Subir',
  'Capture image from Webcam' : 'Capturar imagen con la webcam',
  'Attach File' : 'Adjuntar Archivo',
  'Attach...' : 'Adjuntar...',
  'Config' : 'Configurar',
  'Take Webcam Photo' : 'Capturar foto con Webcam',
  'Authors' : 'Autores',
  'Associated Authors' : 'Autores Relacionados',
  'Edition Date' : 'Fecha de Edición',
  'Professional-Intervention' : 'Profesional-Intervención',
  'Procedures and Materials': 'Materiales y Procedimientos',
  'Materials' : 'Materiales',
  'Procedures' : 'Procedimientos',
  'Biencultural' : 'Bienes Culturales',
  'Material-Intervention' : 'Material-Intervención',
  'Biencultural-Intervention' : 'Bien Cultural-Intervención',
  'Select category' : 'Seleccione Categoría',
  'Category' : 'Categoría',
  'Conservation State' : 'Estado de Conservación',
  'Princ. & Desc' : 'Princ. y Desc.',
  'Theorical Principles': 'Principios Teóricos',
  'Proc. Description' : 'Descripción del Procedimiento',
  'Associations' : 'Asociaciones',
  'Jobs' : 'Cargos',
  'Options Menu': 'Menú de Opciones',
  'Restaurators' : 'Restauradores',
  'Interventions' : 'Intervenciones',
  'Works Of Art' : 'Obras',
  'Partners' : 'Colaboradores',
  'Interventions List' : 'Lista de Intervenciones',
  'Documents List' : 'Lista de Documentos',
  'Works Of Art List' : 'Lista de Obras de Arte',
  'AND': 'Y',
  'OR': 'O',
  'AND NOT': 'Y NO',
  'OR NOT': 'O NO',
  'Select Operator':'Seleccione Operador',
  'More Options': 'Más Opciones',
  'Mark Address': 'Buscar Dirección',
  'Coords': 'Cordenadas',
  'Reference': 'Referencia',
  'Artist': 'Autor',
  'Artist-Work Of Art': 'Autor-Obra de Arte',
  'Add Artist': 'Agregar Autor',
  'Associated Artists': 'Autores Asociados',
  'Warning': 'Atención',
  'This list can contain only one value': 'Esta lista solo puede contener un valor',
  'Duplicated value not allowed' : 'No se permiten valores duplicados',
  'News Board': 'Tablón de Anuncios'
};